DROP DATABASE IF EXISTS EMMA;
CREATE DATABASE EMMA;
USE EMMA;

DROP TABLE IF EXISTS Artikel;
DROP TABLE IF EXISTS Bestand;
DROP TABLE IF EXISTS Bestellung;
DROP TABLE IF EXISTS ArtikelBestellung;
DROP TABLE IF EXISTS Person;
DROP TABLE IF EXISTS Mitarbeiter;

CREATE TABLE Artikel (
	ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	Name VARCHAR(45),
	Preis NUMERIC(38)
) ENGINE = InnoDB;

CREATE TABLE Bestand (
	fiArtikel INT NOT NULL,
	RegalNummer INT,
	PlatzNummer INT,
	FOREIGN KEY (fiArtikel) REFERENCES Artikel(ID) ON DELETE CASCADE
) ENGINE = InnoDB;

CREATE TABLE Bestellung (
	ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	fiPerson INT NOT NULL,
	fiMitarbeiter INT NOT NULL,
	wiederkehrend INT,
	ausfuehrung DATE,
	FOREIGN KEY (fiPerson) REFERENCES Person(ID) ON DELETE CASCADE,
	FOREIGN KEY (fiMitarbeiter) REFERENCES Mitarbeiter(ID) ON DELETE CASCADE
) ENGINE = InnoDB;

CREATE TABLE ArtikelBestellung (
	ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	fiArtikel INT NOT NULL,
	fiBestellung INT NOT NULL,
	FOREIGN KEY (fiArtikel) REFERENCES Artikel(ID) ON DELETE CASCADE,
	FOREIGN KEY (fiBestellung) REFERENCEs Bestellung(ID) ON DELETE CASCADE
) ENGINE = InnoDB;

CREATE TABLE Person (
	ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	Geburtsdatum DATE,
	Str VARCHAR(45),
	Hnr VARCHAR(7),
	Plz CHAR(5),
	Ort VARCHAR(45)
) ENGINE = InnoDB;

CREATE TABLE Mitarbeiter (
	ID INT NOT NULL PRIMARY KEY,
	Benutzername VARCHAR(45) NOT NULL,
	Passwort VARCHAR(45) NOT NULL,
	Status ENUM('Hilfskraft', 'Personal', 'Chef') NOT NULL,
	FOREIGN KEY (ID) REFERENCES Person(ID) ON DELETE CASCADE
) ENGINE = InnoDB;